# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - Feature Request
        - new
        - UI
        - API 
    - title: Bugs
      labels:
        - bug
        - P0 - Urgent
    - title: Core Functionality
      labels:
        - Installation and Upgrade
        - Configuration
    - title: Localization
      labels:
        - Localization
    - title: Inner Beauty
      lables: 
        - development
        - build
        - Code Smell
        - Backend System
        - Package Dependencies
    - title: Other Changes
      labels:
        - "*"