risky: false
version: 8.2
preset: recommended
monolithic: true

tab-width: 4
use-tabs: false

enabled:
- assign_null_coalescing_to_coalesce_equal
- backtick_to_shell_exec
- blank_line_after_namespace

 
disabled:


finder:
  path:
    - "src"
  exclude:
    - "vendor"
  name: "*.php"
