risky: false
version: 8.2
preset: recommended
monolithic: true

tab-width: 4
use-tabs: false

enabled:
- alpha_ordered_imports
 
disabled:


finder:
  path:
    - "src"
  exclude:
    - "vendor"
  name: "*.php"
