# This is the developer docker-compose.yml file. You can build and Run ChurchCRM
# from this file by first filling in your password and db info in the .env
# file and then running "docker-compose -f docker-compose.develop.yaml build", and
# "docker-compose -f docker-compose.develop.yaml up" in your terminal.
version: "3"
services:
  database:
    image: mariadb
    env_file:
      - .env
  churchcrm:
    build:
      context: .
      dockerfile: Dockerfile.churchcrm
    # ports:
    #   - "9000:9000"
    volumes:
      - source:/var/www/html
    env_file:
      - .env
    links:
      - database
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:8080"
    links:
      - churchcrm
    volumes:
      - source:/var/www/html

  mailserver:
    #  Reference: https://blog.mailtrap.io/mailhog-explained/
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  source:
