name: POEditor Locales

on:
  schedule:
    - cron: "0 0 * * *"
      
env:
  node_version: 18

jobs:

  Download:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
    - uses: actions/checkout@v4
      with:
        # fetch full history so things like auto-changelog work properly
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
        registry-url: 'https://registry.npmjs.org'

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
   
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        cd src
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Run Docker
      run: |
        npm run ci-docker-test-start
        docker-compose -f docker/docker-compose.test-php8-apache.yaml ps -a
        docker-compose -f docker/docker-compose.test-php8-apache.yaml logs

    - name: Gen Locales
      run: npm run locale-gen

    - name: Create BuildConfig File
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "BuildConfig.json"
        json: '{"POEditor": { "id": "77079", "token": "${{ secrets.POEDITOR_TOKEN }}"}}'

    - name: Download locales from POEditor
      run: npm run locale-download

    - name: Push changes to ${{ steps.package-version.outputs.current-version}} locale branch
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'locale/${{ steps.package-version.outputs.current-version}}'
        delete-branch: true
        title: "${{ steps.package-version.outputs.current-version}} POEditor Update - ${{ steps.date.outputs.date }}"
        commit-message: 'Loacle Gen & Download on ${{ steps.date.outputs.date }}'
