name: Security Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0

      - name: PHP Security
        uses: symfonycorp/security-checker-action@v2

      - name: Node Security
          uses: ajinabraham/njsscan-action@v5
          with:
            args: '.'
