name: Update Version 
on:
  workflow_dispatch:
    inputs:
      ver:
        description: 'release types (patch, minor, or major)'
        required: true
        default: patch
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm version ${{ github.event.inputs.ver }}
      - run: npm install
