name: Update Version 
on:
  workflow_dispatch:
    inputs:
      ver:
        description: 'release types (patch, minor, or major)'
        required: true
        default: patch
jobs:
  update_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Update package version
        run: npm version ${{ github.event.inputs.ver }}
        
      - name: Update Other versions
        run: npm run updateVersions
