name: Update Version 
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'New Version'
        required: true
        
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
